### ISSUE TITLE
Attempt to unlock request@~2.40.0, which hasn't been locked

### ISSUE THREAD

**Issue by mfojtik** [openshift/sti-nodejs#73] opened 2015-10-29 15:35 UTC
We can see this happening randomly when building applications:

```console
I1028 06:34:08.546426       1 sti.go:393] ---> Installing application source
I1028 06:34:08.562156       1 sti.go:393] ---> Building your Node application from source
E1028 06:34:08.947550       1 sti.go:419] npmnpm  info it worked if it ends with ok
E1028 06:34:08.947675       1 sti.go:419] npm info using npm@1.4.28
E1028 06:34:08.947685       1 sti.go:419] npm info using node@v0.10.35
E1028 06:34:08.947712       1 sti.go:419] info it worked if it ends with ok
E1028 06:34:08.947730       1 sti.go:419] npm info using npm@1.4.28
E1028 06:34:08.947739       1 sti.go:419] npm info using node@v0.10.35
E1028 06:34:09.132334       1 sti.go:419] npm WARN package.json fh-app@0.2.0 No repository field.
E1028 06:34:09.132593       1 sti.go:419] npm WARN package.json fh-app@0.2.0 No repository field.
E1028 06:34:09.134422       1 sti.go:419] npm infonpm info preinstall fh-app@0.2.0
E1028 06:34:09.134479       1 sti.go:419]  preinstall fh-app@0.2.0
E1028 06:34:09.152250       1 sti.go:419] npm ERR! Error: Attempt to unlock request@~2.40.0, which hasn't been locked
E1028 06:34:09.152301       1 sti.go:419] npm ERR!     at unlock (/opt/rh/nodejs010/root/usr/lib/node_modules/npm/lib/utils/locker.js:44:11)
E1028 06:34:09.152311       1 sti.go:419] npm ERR!     at cb (/opt/rh/nodejs010/root/usr/lib/node_modules/npm/lib/cache/add-named.js:32:5)
E1028 06:34:09.152347       1 sti.go:419] npm ERR!npm ERR! Error: Attempt to unlock request@~2.40.0, which hasn't been locked
E1028 06:34:09.152363       1 sti.go:419] npm ERR!     at unlock (/opt/rh/nodejs010/root/usr/lib/node_modules/npm/lib/utils/locker.js:44:11)
E1028 06:34:09.152371       1 sti.go:419] npm ERR!     at cb (/opt/rh/nodejs010/root/usr/lib/node_modules/npm/lib/cache/add-named.js:32:5)
E1028 06:34:09.152384       1 sti.go:419] npm ERR!     at /opt/rh/nodejs010/root/usr/lib/node_modules/npm/lib/cache/add-named.js:41:20
E1028 06:34:09.152404       1 sti.go:419] npm ERR!     at /opt/rh/nodejs010/root/usr/lib/node_modules/npm/lib/utils/locker.js:30:7
E1028 06:34:09.152440       1 sti.go:419] npm     at /opt/rh/nodejs010/root/usr/lib/node_modules/npm/lib/cache/add-named.js:41:20
E1028 06:34:09.152455       1 sti.go:419] npm ERR!     at /opt/rh/nodejs010/root/usr/lib/node_modules/npm/lib/utils/locker.js:30:7
E1028 06:34:09.152482       1 sti.go:419] npm ERR!     at cb (/opt/rh/nodejs010/root/usr/lib/node_modules/lockfile/lockfile.js:149:38)
E1028 06:34:09.152500       1 sti.go:419] npm ERR!     at /opt/rh/nodejs010/root/usr/lib/node_modules/lockfile/lockfile.js:177:38
E1028 06:34:09.152517       1 sti.go:419]  ERR!     at cb (/opt/rh/nodejs010/root/usr/lib/node_modules/lockfile/lockfile.js:149:38)
E1028 06:34:09.152536       1 sti.go:419] npm ERR!     at /opt/rh/nodejs010/root/usr/lib/node_modules/lockfile/lockfile.js:177:38
E1028 06:34:09.152559       1 sti.go:419] npm ERR!     at Object.oncomplete (fs.js:108:15)
E1028 06:34:09.152583       1 sti.go:419] npm ERR!     at Object.oncomplete (fs.js:108:15)
E1028 06:34:09.153135       1 sti.go:419] npm ERR! If you need help, you may report this *entire* log,
E1028 06:34:09.153165       1 sti.go:419] npm ERR! including the npm and node versions, at:
E1028 06:34:09.153175       1 sti.go:419] npm ERR!      Try: 0. Ongoing build with phase: Running
```

After this the assemble script fails. Restarting the build fixes this problem. Is there something we can do with npm @humaton @eliskasl ?

CC @david-martin

**Comment by mfojtik** [comment] 2015-10-29 15:41
@humaton https://github.com/npm/npm/issues/4815#issuecomment-145340041 it seems like this might be the solution for this, but I'm not nodejs expert :)

**Comment by david-martin** [comment] 2015-10-29 21:23
Very similar issue reported in this version of npm (1.4.28) here https://github.com/npm/npm/issues/5948#issuecomment-90211209
No resolution at this time, but it looks like a timing issue while npm is preparing or building up a list of whats in its cache

**Comment by david-martin** [comment] 2015-10-30 11:28
@humaton @mfojtik  After doing some digging and getting feedback from npm team, it sounds like the issue is confine to npm 1. Is it possible to get npm 2 or 3 into the sti-nodejs image?
For now, i've built the sti-nodejs image locally with a change to upgrade to npm 2.14.9, and I'm using this image to avoid the lock issue.

**Comment by bparees** [comment] 2015-10-30 13:44
We need the SCL package to be updated to pick up the new npm.  @hhorak what can you tell us about that?

**Comment by hhorak** [comment] 2015-10-30 14:14
Hm, this is sad. To my knowledge, we don't plan to update npm to something newer than 1.4.28 in nodejs010 SCL, because npm comes with a loooots of dependencies and it would be ... challenging at least... We'll rather provide a new collection based on nodejs 4.x or newer instead, that's what we focus now.

**Comment by bparees** [comment] 2015-12-18 21:18
should be fixed now, SCL did pick up the fix and we've respun the image w/ the fix.  reopen if you hit it again (with a current image), please.

**Closed by bparees** 2015-12-18 21:18 UTC

**Comment by david-martin** [comment] 2016-01-22 14:11
@bparees can you confirm if the next scl release will have node0.10 with npm v2?

**Comment by bparees** [comment] 2016-01-22 14:53
@david-martin that'd be for @hhorak to confirm.

**Comment by eliskasl** [comment] 2016-01-22 15:12
@david-martin, nodejs010 with npm v2 was shipped shortly before Christmas, but it seems the update didn't make it in the rebuilt image for some reason.
For CentOS, we'll be delivering a new collection with the nodejs 4.x LTS release soon.

**Comment by hhorak** [comment] 2016-01-22 15:23
And as for the updated npm in nodejs010 in CentOS, we still don't have the process of rebuilding packages in CentOS automatically, so reason why it's not there already might be just that.. I'll take a look at it next week and make sure that whatever is out in RHSCL, it will be available also in CentOS.
